### ISSUE TITLE
It's broken 😿

### ISSUE THREAD

**Issue by thearnica** [zzarcon/ts-react-toolbox#3]
Hey! Trying to lint, and there is no tslint. Trying to build and there is no tsc.
```
node_modules/ts-react-toolbox/node_modules/.bin/tsc ENOENT
```
and there is no `node_modules` in ts-react-toolbox at all.

**Comment by zzarcon** [comment]
Hi @thearnica ! Thanks for reporting the issue, do you mind sharing:

* ts-react-toolbox version
* Node.js version
* npm/yarn version

To me there is no **node_modules/ts-react-toolbox/node_modules/.bin/tsc** either, instead yarn or npm will put **tsc** or **tslint** on the root as?

```
node_modules/.bin/tsc
```
And later ts-react-toolbox will resolved there

**Comment by thearnica** [comment]
Hi,
- ts-react-toolbox version 0.4 - 1
- Node.js version: 9
- npm/yarn version: 5, and with or without yarn (I’ve installed it cos a few commands used yarn)

So we have the same location for tsc, but in my case (it might be related to PATH, I always have to run ./node_modulues/bin/.gulp for example), execution falls.

PS: But there is also an issue with tsconfig.prod, also referrer from ts dirrectory. It does exists, but there is no way to change it, and add custim typings, for example

**Comment by zzarcon** [comment]
Interesting... what I will recommend is ```$ yarn update ts-react-toolbox --latest``` that should force it to use the **0.1.10**.

We already support custom typings, they go under **custom-typings** folder in the root, check this project for an example https://github.com/zzarcon/video-snapshot/blob/master/tsconfig.json

Let me know if that works :)

**Comment by thearnica** [comment]
...Ok, custom typings do work. When you yarn dev, but then you yarn release it will use bundled tsconfig.prod.json
https://github.com/zzarcon/ts-react-toolbox/blob/master/tsconfig.prod.json
And it does not extend mine one, or include typings from my dir

To say more - I had to move them in src to be able to build library 
https://github.com/thearnica/react-media-match/tree/master/src/custom-typings

**Comment by theKashey** [comment]
Shall we close this?

**Comment by zzarcon** [comment]
Not sure, @thearnica can we? 🤞

**Comment by theKashey** [comment]
Pretty sure `npm` was an issue. Could confirm - it's now working for her.
